Repository ducvui2003/ecommerce, pull requests merged in 2025-06, with the labels that each got.

#144 Feat: Fix bug the quantity of cart item is not updated correctly.
  server/package-lock.json
  server/package.json
  server/src/routes/cart/cart.dto.ts
  server/src/routes/cart/cart.repository.ts
  server/src/routes/cart/cart.service.ts
  web/package-lock.json
  web/src/app/cart/page.tsx
  web/src/app/contact/layout.tsx
  web/src/app/contact/page.tsx
  web/src/app/product/detail/[id]/ProductDetail.tsx
  web/src/components/CartDropdown.tsx
  web/src/components/Navigation.tsx
  web/src/components/QuantitySelector.tsx
  web/src/components/SearchBar.tsx
  web/src/features/cart/cart.api.ts
  web/src/features/product/product.api.ts
  web/src/features/promotion/promotion.api.ts
  web/src/lib/store.ts
  web/src/service/cart.service.ts
  web/src/service/product.service.ts
  web/src/types/cart.type.ts
  web/src/types/contact.type.ts
  web/src/types/product.type.ts
  web/src/types/schema/contact.schema.ts
Labels: bug

#150 Feat/get new product
  server/src/routes/product/interfaces/product-repository.interface.ts
  server/src/routes/product/product.controller.ts
  server/src/routes/product/product.repository.ts
  server/src/routes/product/product.service.ts
  web/src/app/home/FeatureSection.tsx
  web/src/app/home/NewSection.tsx
  web/src/app/home/SellerSection.tsx
  web/src/app/home/StorySection.tsx
  web/src/app/home/StorySection2.tsx
  web/src/app/home/page.tsx
  web/src/components/CartDropdown.tsx
  web/src/features/product/product.api.ts
Labels: enhancement

#153 Release v1.2a
  .github/workflows/web-ci.yml
  .gitignore
  docker/.gitignore
  docker/README.md
  docker/certbot/get-cert.sh
  docker/env/example.db.env
  docker/env/example.server.env
  docker/env/example.web.env
  docker/example.docker-compose.yml
  docker/init/postgres/01_schema.sql
  docker/init/postgres/02_data.sql
  docker/nginx/nginx.conf
  server/Dockerfile
  server/docs/swagger.yaml
  server/src/configs/env.config.ts
  server/src/configs/swagger.config.ts
  server/src/main.ts
  server/src/routes/order/order.schema.ts
  server/src/routes/product/interfaces/product-repository.interface.ts
  server/src/routes/product/product.controller.ts
  server/src/routes/product/product.repository.ts
  server/src/routes/product/product.service.ts
  web/.gitignore
  web/Dockerfile
  web/package-lock.json
  web/src/app/(user)/user/info/page.tsx
  web/src/app/api/auth/callback/facebook/route.ts
  web/src/app/api/auth/callback/google/route.ts
  web/src/app/home/FeatureSection.tsx
  web/src/app/home/NewSection.tsx
  web/src/app/home/SellerSection.tsx
  web/src/app/home/StorySection.tsx
  web/src/app/home/StorySection2.tsx
  web/src/app/home/page.tsx
  web/src/components/CartDropdown.tsx
  web/src/components/auth/signInFacebook.ts
  web/src/components/auth/signInGoogle.ts
  web/src/components/oauth2/GoogleButton.tsx
  web/src/config/env.config.ts
  web/src/features/product/product.api.ts
  web/src/lib/http.client.ts
  web/src/lib/http.server.ts
  web/src/lib/logger.ts
  web/src/lib/server.helper.ts
  web/src/service/auth.service.ts
  web/src/service/cart.service.ts
  web/src/service/comment.service.ts
  web/src/service/oauth2.service.ts
  web/src/service/user.server.service.ts
  web/src/service/user.service.ts
Labels: documentation, enhancement, good first issue

#160 Release v1.2b
  docker/README.md
  docker/generate-ssl.sh
  docker/nginx/nginx.conf
  docker/nginx/nginx.temp.conf
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/configs/websocker.config.ts
  server/src/main.ts
  server/src/routes/payment/payment.controller.ts
  server/src/routes/payment/payment.repository.ts
  server/src/routes/payment/payment.service.ts
  server/src/shared/repositories/shared-product.repository.ts
  server/src/shared/services/payment/vnpay.service.ts
  server/src/shared/services/websocket.service.ts
  server/src/shared/shared.module.ts
  server/src/websockets/payment.gateway.ts
  server/src/websockets/websocket.adapter.ts
  server/src/websockets/websocket.module.ts
  web/.gitignore
  web/Dockerfile
  web/next.config.ts
  web/package-lock.json
  web/package.json
  web/src/app/(user)/user/order/column.tsx
  web/src/app/api/payment/vnpay/route.ts
  web/src/app/contact/layout.tsx
  web/src/app/contact/page.tsx
  web/src/app/globals.css
  web/src/app/order/OrderPayment.tsx
  web/src/app/order/form.tsx
  web/src/app/order/qr-code.tsx
  web/src/app/order/socket.ts
  web/src/components/Navigation.tsx
  web/src/components/OrderDetailSheet.tsx
  web/src/components/address/SelectDistrict.tsx
  web/src/components/address/SelectProvince.tsx
  web/src/components/address/SelectWard.tsx
  web/src/features/order/order.slice.ts
  web/src/service/address.service.ts
Labels: bug, documentation, enhancement, good first issue

#165 Feature/get most view product
  server/prisma/migrations/20250609162625_add_view_column_in_product_table/migration.sql
  server/prisma/schema.prisma
  server/src/routes/product/interfaces/product-repository.interface.ts
  server/src/routes/product/product.controller.ts
  server/src/routes/product/product.repository.ts
  server/src/routes/product/product.schema.ts
  server/src/routes/product/product.service.ts
  server/src/shared/models/product.model.ts
  web/src/app/about-us/CoreValuesSection.tsx
  web/src/app/home/MostViewSection.tsx
  web/src/app/home/page.tsx
  web/src/app/product/detail/[id]/ProductDetail.tsx
  web/src/app/product/detail/[id]/ProductInfo.tsx
  web/src/features/product/product.api.ts
  web/src/types/product.type.ts
Labels: enhancement

#189 Fix/env
  server/package-lock.json
  server/package.json
  server/prisma/dbml/awesome.dbml
  server/prisma/erd/ERD.pdf
  server/prisma/erd/ERD.png
  server/prisma/schema.prisma
  server/src/configs/env.config.ts
  web/src/components/ProductCard.tsx
  web/src/types/product.type.ts
Labels: bug

#194 Fix/button dropdown
  web/src/components/ManagerDropdown.tsx
  web/src/components/UserDropdown.tsx
Labels: bug
